# docker-compose.yml
version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src/myradar:/var/www/html/myradar
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src/myradar:/var/www/html/myradar
    working_dir: /var/www/html/myradar
    
  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ./src/myradar:/var/www/html/myradar
    working_dir: /var/www/html/myradar

    links:
      - php
  
  